name: just_another_stopwatch
description: Just another stopwatch app made with Dart/Flutter and love <3.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: fonts/WorkSans-Light.ttf
          weight: 300
        - asset: fonts/WorkSans-Thin.ttf
          weight: 100